name: macos

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-15]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure GamespySDK
      run: |
        cmake --preset macos
        
    - name: Build GamespySDK
      run: |
        cmake --build build
